### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 98: unexpected end of data

### ISSUE THREAD

**Issue by amirj** [google/seq2seq#170]
I'm going to train a char-level NMT model, using the following config file:
```
model: AttentionSeq2Seq
model_params:
  attention.class: seq2seq.decoders.attention.AttentionLayerBahdanau
  attention.params:
    num_units: 512
  bridge.class: seq2seq.models.bridges.ZeroBridge
  embedding.dim: 512
  encoder.class: seq2seq.encoders.BidirectionalRNNEncoder
  encoder.params:
    rnn_cell:
      cell_class: LSTMCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 2
  decoder.class: seq2seq.decoders.AttentionDecoder
  decoder.params:
    rnn_cell:
      cell_class: LSTMCell
      cell_params:
        num_units: 512
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 4
  optimizer.name: Adam
  optimizer.params:
    epsilon: 0.0000008
  optimizer.learning_rate: 0.0001
  source.max_seq_len: 50
  source.reverse: false
  target.max_seq_len: 100
  vocab_source: ../data/vocab.char
  vocab_target: ../data/vocab.char
input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_delimiter: ''
    target_delimiter: ''
    source_files:
      - ../data/train.source
    target_files:
      - ../data/train.target
input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_delimiter: ''
    target_delimiter: ''
    source_files:
      - ../data/valid.source
    target_files:
      - ../data/valid.target
buckets: 100,200,300
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: TrainSampleHook
    params:
      every_n_steps: 1000
      source_delimiter: ''
      target_delimiter: ''
default_params: &default_params
  - separator: ""
metrics:
  - class: LogPerplexityMetricSpec
  - class: BleuMetricSpec
    params:
      <<: *default_params
  - class: RougeMetricSpec
    params:
      <<: *default_params
      rouge_type: rouge_1/f_score
  - class: RougeMetricSpec
    params:
      <<: *default_params
      rouge_type: rouge_1/r_score
  - class: RougeMetricSpec
    params:
      <<: *default_params
      rouge_type: rouge_1/p_score
  - class: RougeMetricSpec
    params:
      <<: *default_params
      rouge_type: rouge_2/f_score
  - class: RougeMetricSpec
    params:
      <<: *default_params
      rouge_type: rouge_2/r_score
  - class: RougeMetricSpec
    params:
      <<: *default_params
      rouge_type: rouge_2/p_score
  - class: RougeMetricSpec
    params:
      <<: *default_params
      rouge_type: rouge_l/f_score
batch_size: 32
train_steps: 100000
eval_every_n_steps: 500000
save_checkpoints_steps: 500
output_dir: ../model

```

The following error is happen:

```

UNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNK
<UNICODE CHARACTERS>SEQUENCE_END

====================================================================================================


INFO:tensorflow:global_step/sec: 0.950409
INFO:tensorflow:loss = 0.391771, step = 6101
INFO:tensorflow:global_step/sec: 0.898042
INFO:tensorflow:loss = 0.594752, step = 6201
INFO:tensorflow:global_step/sec: 0.870135
INFO:tensorflow:loss = 0.43002, step = 6301
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 77904026 get requests, put_count=77904146 evicted_count=65000 eviction_rate=0.000834359 and unsatisfied allocation rate=0.000837466
INFO:tensorflow:global_step/sec: 0.724903
INFO:tensorflow:loss = 0.805614, step = 6401
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 79266182 get requests, put_count=79266247 evicted_count=75000 eviction_rate=0.000946178 and unsatisfied allocation rate=0.000949926
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 80575459 get requests, put_count=80575581 evicted_count=85000 eviction_rate=0.00105491 and unsatisfied allocation rate=0.00105789
INFO:tensorflow:Saving checkpoints for 6501 into ../model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.666884
INFO:tensorflow:loss = 1.13433, step = 6501
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 81935867 get requests, put_count=81936036 evicted_count=95000 eviction_rate=0.00115944 and unsatisfied allocation rate=0.0011618
INFO:tensorflow:global_step/sec: 0.682995
INFO:tensorflow:loss = 0.864229, step = 6601
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 83281182 get requests, put_count=83281337 evicted_count=105000 eviction_rate=0.00126079 and unsatisfied allocation rate=0.00126327
INFO:tensorflow:global_step/sec: 0.682503
INFO:tensorflow:loss = 0.882166, step = 6701
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 84606512 get requests, put_count=84606675 evicted_count=115000 eviction_rate=0.00135923 and unsatisfied allocation rate=0.00136159
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 85949875 get requests, put_count=85950025 evicted_count=125000 eviction_rate=0.00145433 and unsatisfied allocation rate=0.0014568
INFO:tensorflow:global_step/sec: 0.684397
INFO:tensorflow:loss = 0.869902, step = 6801
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 87312323 get requests, put_count=87312396 evicted_count=135000 eviction_rate=0.00154617 and unsatisfied allocation rate=0.00154948
INFO:tensorflow:global_step/sec: 0.684574
INFO:tensorflow:loss = 0.877229, step = 6901
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 88653476 get requests, put_count=88653557 evicted_count=145000 eviction_rate=0.00163558 and unsatisfied allocation rate=0.00163875
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 89959527 get requests, put_count=89959653 evicted_count=155000 eviction_rate=0.00172299 and unsatisfied allocation rate=0.00172562
INFO:tensorflow:Saving checkpoints for 7001 into ../model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.656726
INFO:tensorflow:loss = 0.792112, step = 7001
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/amir/projects/engine/seq2seq/bin/train.py", line 276, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/amir/projects/engine/seq2seq/bin/train.py", line 271, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 106, in run
    return task()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 459, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 281, in train
    monitors=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 280, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 426, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 984, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 899, in run
    run_metadata=run_metadata))
  File "/home/amir/projects/engine/seq2seq/seq2seq/training/hooks.py", line 219, in after_run
    target_slice).decode("utf-8") + "\n\n"
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 98: unexpected end of data

```

**Comment by amirj** [comment]
This issue is related to #153

**Comment by dennybritz** [comment]
Yes, seems like the same issue. Closing for now. #96 may help you, but I'm still not sure how to fix this the right way.

**Comment by shubhamagarwal92** [comment]
Do you have special characters in your text file? I think in general we would not face this issue when we use the model for word level processing (as space (' ') would be used as delimiter).  

As mentioned, I would suggest three possible solutions for using the current code base:
1. Convert your special characters into "temporary" replacement (ascii) characters (not used in the text).
2. Convert your text into sequence of integers. (I provided a gist in #153 )
3. If you also want to evaluate the predictions during training, change the file encoding from 'utf-8' to latin-1 for the three files mentioned in #153. (Also for create vocabulary file. Although neither stable and nor recommended, this can be used for the time being.) 

@dennybritz what challenges could we face if we read the file in unicode (line.decode('utf-8')), do all the processing and convert just at the time of writing results (line.decode('utf-8'))? For this, I think there would be multiple changes wherever you have used these (encode/decode) tags. I would look more into this issue till then.

**Comment by kaihuchen** [comment]
Has there been any resolution to this problem? I am seeing a similar problem but with a slight twist. In my case:

* Was able to train a character-level NMT model without problem. Both source and target files in UTF8 encoding, using python3 throughout. The model converges slowly and steadily, all look normal.
* However, when doing prediction I then see the **UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 0: unexpected end of data** message (where the **0xe8** part varies depends on what I have in the test source)

My observations:

1. If I change the test data to contain only English, then error does not occur, but then the prediction result contains gibberish as expected (since the model was never trained in English)
2. If I insert even one Unicode character anywhere into the test data file, then the error shows up. Note that the model was trained entirely in Unicode at character level.
3. For prediction (see my script below) if I change the parameter source_delimiter to ' ' (i.e., the ASCII space character, as opposed to using an empty string to enforce character-level prediction) then the problem error does not happen, but then the predicted output contains only gibberish as expected (since the model was trained with delimiter set to the empty string).

Anybody has insight on how to deal with this problem?

Here is my training script:
<pre>
#!/bin/bash
BASE=/home/kaihu/ml/tests/seq2seq
BASE2=.

TRAIN_SOURCES=${BASE2}/train/sources.txt
TRAIN_TARGETS=${BASE2}/train/targets.txt
VOCAB_SOURCE=${BASE2}/train/vocab.sources.txt
VOCAB_TARGET=${BASE2}/train/vocab.targets.txt
DEV_SOURCES=${BASE2}/dev/sources.txt
DEV_TARGETS=${BASE2}/dev/targets.txt

MODEL_DIR=${BASE2}/models

python3 ${BASE}/bin/train.py --config_paths ${BASE}/example_configs/nmt_conv_small.yml \
  --model_params "
      vocab_source: $VOCAB_SOURCE
      vocab_target: $VOCAB_TARGET" \
  --input_pipeline_train "
    class: ParallelTextInputPipeline
    params:
      source_delimiter: ''
      source_files:
        - $TRAIN_SOURCES
      target_delimiter: ''
      target_files:
        - $TRAIN_TARGETS" \
  --input_pipeline_dev "
    class: ParallelTextInputPipeline
    params:
      source_delimiter: ''
      source_files:
        - $DEV_SOURCES
      target_delimiter: ''
      target_files:
        - $DEV_TARGETS" \
  --batch_size 64 \
  --gpu_allow_growth True \
  --train_steps 1000000 \
  --eval_every_n_steps 2000 \
  --output_dir $MODEL_DIR
</pre>
 
Here is my prediction script:
<pre>
#!/bin/bash
BASE=/home/kaihu/ml/tests/seq2seq
MODEL_DIR=./models 

DEV_SOURCES=./dev/sources.txt
export PRED_DIR=.

python3 ${BASE}/bin/infer.py \
  --tasks "
    - class: DecodeText
      params:
        delimiter: ''
        unk_replace: False" \
  --model_dir $MODEL_DIR \
  --input_pipeline "
    class: ParallelTextInputPipeline
    params:
      source_delimiter: ''
      source_files:
        - $DEV_SOURCES" \
  >  ${PRED_DIR}/predictions.txt
</pre>
 
Here is the trace from running the prediction script:
<pre>
$ ./predict 
INFO:tensorflow:Creating ParallelTextInputPipeline in mode=infer
INFO:tensorflow:
ParallelTextInputPipeline:
  num_epochs: 1
  shuffle: false
  source_delimiter: ''
  source_files: [./dev/sources.txt]
  target_delimiter: ' '
  target_files: []

INFO:tensorflow:Creating AttentionSeq2Seq in mode=infer
INFO:tensorflow:
AttentionSeq2Seq:
  attention.class: seq2seq.decoders.attention.AttentionLayerBahdanau
  attention.params: {num_units: 128}
  bridge.class: seq2seq.models.bridges.ZeroBridge
  bridge.params: {}
  decoder.class: seq2seq.decoders.AttentionDecoder
  decoder.params:
    rnn_cell:
      cell_class: GRUCell
      cell_params: {num_units: 128}
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 1
  embedding.dim: 128
  embedding.init_scale: 0.04
  embedding.share: false
  encoder.class: seq2seq.encoders.ConvEncoder
  encoder.params: {attention_cnn.kernel_size: 3, attention_cnn.layers: 6, attention_cnn.units: 128,
    output_cnn.kernel_size: 3, output_cnn.layers: 3, output_cnn.units: 128, position_embeddings.combiner_fn: tensorflow.multiply,
    position_embeddings.enable: true, position_embeddings.num_positions: 52}
  inference.beam_search.beam_width: 0
  inference.beam_search.choose_successors_fn: choose_top_k
  inference.beam_search.length_penalty_weight: 0.0
  optimizer.clip_embed_gradients: 0.1
  optimizer.clip_gradients: 5.0
  optimizer.learning_rate: 0.0001
  optimizer.lr_decay_rate: 0.99
  optimizer.lr_decay_steps: 100
  optimizer.lr_decay_type: ''
  optimizer.lr_min_learning_rate: 1.0e-12
  optimizer.lr_staircase: false
  optimizer.lr_start_decay_at: 0
  optimizer.lr_stop_decay_at: 2147483647
  optimizer.name: Adam
  optimizer.params: {}
  optimizer.sync_replicas: 0
  optimizer.sync_replicas_to_aggregate: 0
  source.max_seq_len: 50
  source.reverse: false
  target.max_seq_len: 50
  vocab_source: ./train/vocab.sources.txt
  vocab_target: ./train/vocab.targets.txt

INFO:tensorflow:Creating DecodeText in mode=infer
INFO:tensorflow:
DecodeText: {delimiter: '', postproc_fn: '', unk_mapping: null, unk_replace: false}

INFO:tensorflow:Creating vocabulary lookup table of size 3711
INFO:tensorflow:Creating vocabulary lookup table of size 3711
INFO:tensorflow:Creating ConvEncoder in mode=infer
INFO:tensorflow:
ConvEncoder: {attention_cnn.kernel_size: 3, attention_cnn.layers: 6, attention_cnn.units: 128,
  embedding_dropout_keep_prob: 0.8, output_cnn.kernel_size: 3, output_cnn.layers: 3,
  output_cnn.units: 128, position_embeddings.combiner_fn: tensorflow.multiply, position_embeddings.enable: true,
  position_embeddings.num_positions: 52}

INFO:tensorflow:Creating AttentionLayerBahdanau in mode=infer
INFO:tensorflow:
AttentionLayerBahdanau: {num_units: 128}

INFO:tensorflow:Creating AttentionDecoder in mode=infer
INFO:tensorflow:
AttentionDecoder:
  init_scale: 0.04
  max_decode_length: 100
  rnn_cell:
    cell_class: GRUCell
    cell_params: {num_units: 128}
    dropout_input_keep_prob: 0.8
    dropout_output_keep_prob: 1.0
    num_layers: 1
    residual_combiner: add
    residual_connections: false
    residual_dense: false

INFO:tensorflow:Creating ZeroBridge in mode=infer
INFO:tensorflow:
ZeroBridge: {}

2017-09-20 10:30:25.813803: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 10:30:25.813824: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 10:30:25.813831: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 10:30:25.813836: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 10:30:25.813841: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-20 10:30:25.816217: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2017-09-20 10:30:25.816249: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: turing5
2017-09-20 10:30:25.816256: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: turing5
2017-09-20 10:30:25.816282: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.82.0
2017-09-20 10:30:25.816303: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.82  Wed Jul 19 21:16:49 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
"""
2017-09-20 10:30:25.816317: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.82.0
2017-09-20 10:30:25.816323: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.82.0
INFO:tensorflow:Restoring parameters from ./models/model.ckpt-210003
INFO:tensorflow:Restored model from ./models/model.ckpt-210003
Traceback (most recent call last):
  File "/home/kaihu/ml/tests/seq2seq/bin/infer.py", line 129, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/kaihu/ml/tests/seq2seq/bin/infer.py", line 125, in main
    sess.run([])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 980, in run
    run_metadata=run_metadata))
  File "/home/kaihu/ml/tests/seq2seq/seq2seq/tasks/decode_text.py", line 165, in after_run
    fetches["features.source_tokens"].astype("S"), "utf-8")
  File "/home/kaihu/.local/lib/python3.5/site-packages/numpy/core/defchararray.py", line 505, in decode
    _vec_string(a, object_, 'decode', _clean_args(encoding, errors)))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 0: unexpected end of data
</pre>
